name: Windows

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: call dev prompt
      run: dir && dev_tools.bat
    - name: make
      run: md build && cd build && cmake -G"NMake Makefiles" .. && nmake
